# Generated by Django 6.1 on 2026-09-25 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='planting',
            name='barcode',
        ),
    ]
