# Generated by Django 6.1 on 2026-09-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_remove_packet_barcode_remove_plant_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packet',
            name='expiry',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
