# Generated by Django 6.1 on 2026-09-25 05:13

import garden.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_alter_packet_expiry_alter_planting_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=(garden.models.BarcodeMixin, models.Model),
        ),
    ]
