# Generated by Django 6.1 on 2026-09-25 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='garden.container'),
        ),
    ]
