# Generated by Django 6.1 on 2026-09-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_packet_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
