# Generated by Django 6.1 on 2026-09-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0006_plant_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packet',
            name='location',
        ),
    ]
