# Generated by Django 6.1 on 2026-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_remove_packet_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
