# Generated by Django 6.1 on 2026-09-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0009_sheetchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetchangelog',
            name='column_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
