# Generated by Django 5.0.2 on 2024-02-24 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('barcode', models.CharField(max_length=10)),
                ('spacing', models.CharField(blank=True, max_length=10, null=True)),
                ('germination', models.CharField(blank=True, max_length=10, null=True)),
                ('harvest', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('planted', models.DateField()),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='garden.packet')),
            ],
        ),
    ]
